### ISSUE TITLE
左右两种图片的显示位置是否可以被中间的图片遮罩部分？

### ISSUE THREAD

**Issue by nances** [pinguo-zhouwei/MZBannerView#1]
private int mMZModePadding = 0; 这个设置是不是显示左右两张图的位置的间距？

**Comment by pinguo-zhouwei** [comment]
这个暂时还实现不了，试了一下，中间的可以盖住左边的部分，但是右边的布局会显示在中间的上层，而不是下层，估计要要修改ViewPager源码才行

**Comment by liuyuejinqiu** [comment]
@pinguo-zhouwei 不用改源码，ViewPager提供方法，重写，约束绘制顺序即可。我已经实现了，可交流参考

**Comment by pinguo-zhouwei** [comment]
@liuyuejinqiu,可以加我QQ交流一下（QQ:549826574）

**Comment by nances** [comment]
@pinguo-zhouwei  我这边也改了的，但是发现了一个问题，最后一张图和最前面一张图连串的地方有问题，目前还没时间去写

**Comment by nances** [comment]
@liuyuejinqiu  能分享一下吗？谢谢 （QQ:459451429）

**Comment by liuyuejinqiu** [comment]
@nances @pinguo-zhouwei 不好意思呀，之前练手的，现在发现了些问题，等我优化好了，会分享给大家的，最近时间有点紧。

**Comment by nances** [comment]
@liuyuejinqiu  好的

**Comment by liuyuejinqiu** [comment]
@nances @pinguo-zhouwei 我在简书上简单的分析了下原理：http://www.jianshu.com/p/e67aa68d2766

**Comment by nances** [comment]
@liuyuejinqiu 我看了一下，写的挺好的，再写全一点，可以上GITHUB了， @pinguo-zhouwei 你的MZBANNER可以跟这个优化一下， 😄

**Comment by liuyuejinqiu** [comment]
@nances已经上传至github,可直接gradle引入，与普通viewpager相比基本无异。

**Comment by nances** [comment]
@liuyuejinqiu  比如我小于三种图片，如何强制添加左右两张，让他小于三张的时候依然有轮播滚动的效果

**Comment by liuyuejinqiu** [comment]
@nances我只写了最基础的viewpager部分，轮播及其他逻辑的封装可以自己实现或者参考当前MZBannerView中的轮播逻辑做进一步的封装。

**Comment by nances** [comment]
@liuyuejinqiu  好的

**Comment by zhaichuankai** [comment]
这个方法添加带圆角的图片  
如果只缩放y轴  会让圆角变形  
如果同时缩放    加上位移，动画就显得不是很流畅
