### ISSUE TITLE
没有出现魅族效果还是现实普通样式

### ISSUE THREAD

**Issue by sunyuanfei** [pinguo-zhouwei/MZBannerView#10]
![image](https://user-images.githubusercontent.com/7675592/27783886-9cb6365a-600a-11e7-8452-f6d951984ec1.png)

**Comment by pinguo-zhouwei** [comment]
如果 pages 小于3，则自动为普通模式，你看一下你的数据呢

**Comment by sunyuanfei** [comment]
ok
