### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by CatyVon** [pinguo-zhouwei/MZBannerView#110]
您好  个人练习  发现您的库很适合  所以就在项目中使用到了  按照您的说明  使用本地数据  可以使用魅族模式轮播 但是当图片换成自己搭建的后台获取的路径字符串是  一直提示类型转换异常  我是将之前本地数据集合换成了字符串的集合  而且BannerViewHolder实现的接口也改成字符串的泛型  但是依旧出现这个错误  实在无法解决  所以请教您一下  麻烦帮忙回复一下

java.lang.ClassCastException: java.lang.Integer cannot be cast to String
        at com.zedai.love_leader.widget.BannerViewHolder.onBind(BannerViewHolder.java:15)
        at com.zhouwei.mzbanner.MZBannerView$MZPagerAdapter.getView(MZBannerView.java:654)
        at com.zhouwei.mzbanner.MZBannerView$MZPagerAdapter.instantiateItem(MZBannerView.java:595)

**Comment by pinguo-zhouwei** [comment]
错误很明显，BannerViewHolder 15行，类型转换出错，网络图片你用第三方库加载显示就好，不能直接用ImageView.setImageResouce()，Demo 中有加载网络图片的例子，你可以看看

**Comment by CatyVon** [comment]
我看了DEMO里的设置网路图片  DEMO重视设置了MOVIE元素的list集合  我这边是将获取到的路径作为参数装入list集合  并且是根据DEMO的格式  泛型定义的都是String  我设置图片用的Glide  目前都是这个类型转换错误  即使我将自己封装的JaveBean装入list也是类型转换错误  Integer不成转换为BannerEntity这样的  实在麻烦您了

发送自 Windows 10 版邮件应用

发件人: JayZhou
发送时间: 2019年7月29日 16:31
收件人: pinguo-zhouwei/MZBannerView
抄送: Monce; Author
主题: Re: [pinguo-zhouwei/MZBannerView] ClassCastException (#110)

错误很明显，BannerViewHolder 15行，类型转换出错，网络图片你用第三方库加载显示就好，不能直接用ImageView.setImageResouce()，Demo 中有加载网络图片的例子，你可以看看

**Comment by pinguo-zhouwei** [comment]
把你BannerViewHolder 的代码贴出来

**Comment by CatyVon** [comment]
public class BannerViewHolder<String> implements MZViewHolder<String> {

    private ImageView mImageView;

    @Override
    public View createView(Context context) {
        View view = LayoutInflater.from(context).inflate(R.layout.banner_item, null);
        mImageView = (ImageView) view.findViewById(R.id.banner_image);
        return view;
    }

    @Override
    public void onBind(Context context, int position, String imgSource) {
        Glide.with(context).load(imgSource).error(R.mipmap.exchange_img).into(mImageView);
//        mImageView.setImageResource(imgSource);
    }
}

貌似给BannerViewHolder 添加来的 <String> 就不闪退了  剩下貌似就是图片加载不出的问题了  不过谢谢您了

发送自 Windows 10 版邮件应用

发件人: JayZhou
发送时间: 2019年7月29日 17:26
收件人: pinguo-zhouwei/MZBannerView
抄送: Monce; Author
主题: Re: [pinguo-zhouwei/MZBannerView] ClassCastException (#110)

把你BannerViewHolder 的代码贴出来
