### ISSUE TITLE
关于指示器能否设置lp呢，呜呜现在想搞一下指示器位置

### ISSUE THREAD

**Issue by 357847847** [pinguo-zhouwei/MZBannerView#19]
现在指示器只有你的默认三种吗，能否设计一下修改指示器位置呢，这个是否困难，谢谢？

**Comment by pinguo-zhouwei** [comment]
你是想随意调整指示器的位置吗？下个版本我改一下吧

**Comment by 357847847** [comment]
是的，因为看了一下那个设置指示器位置的那个函数，感觉也是通过设置lp来直接设置位置的，所以如果能弄一下就更好了，十分感谢谢，这个控件做的很不错呢。

**Comment by pinguo-zhouwei** [comment]
好的，记下了，下个版本改。

**Comment by 357847847** [comment]
谢谢

**Comment by pinguo-zhouwei** [comment]
已经在v2.0.1版本修改，fixs #29
