### ISSUE TITLE
您好~是否能加一个动态改变指示器drawable的接口。这样想改变指示器颜色会方便点

### ISSUE THREAD

**Issue by zhang8897** [pinguo-zhouwei/MZBannerView#23]

**Comment by pinguo-zhouwei** [comment]
现在已经有了哈，Demo 里面就有，方法叫 setIndicatorRes(int unSelectRes,int selectRes)，接受drawable,不过这儿还有优化空间，加上直接设置颜色的方法。

**Comment by zhang8897** [comment]
哈哈，看到了多谢，给力
