### ISSUE TITLE
setPages之后再setBannerPageClickListener有遇到过无法响应点击

### ISSUE THREAD

**Issue by 357847847** [pinguo-zhouwei/MZBannerView#24]
setPages之后再setBannerPageClickListener有遇到过无法响应点击，这样做会遇到无法点击，我把setBannerPageClickListener放到setPages之前即可，嘿嘿这里不注意还不容易发现呢。

**Comment by pinguo-zhouwei** [comment]
是的，其他配置都在setPages 之前调用吧
