### ISSUE TITLE
有没有点击每一张图片的方法

### ISSUE THREAD

**Issue by duboAndroid** [pinguo-zhouwei/MZBannerView#27]

**Comment by Moosphan** [comment]
你使用setBannerClickListener方法点击有反应吗?

**Comment by Moosphan** [comment]
你在ViewHolder的onBind()方法中设置一下imageview的监听器就可以了,需要在item布局中先设置可点击onclickable=true

**Comment by duboAndroid** [comment]
好的，谢谢，我试下

**Comment by duboAndroid** [comment]
setBannerClickListener这个不能用你这个viewHolder貌似不好弄吧，调不起方法

**Comment by duboAndroid** [comment]
方便加我QQ看下嘛，277627117

**Comment by pinguo-zhouwei** [comment]
setBannerClickListener 这个方法可以用哈，在setPages 前面调用

**Comment by duboAndroid** [comment]
我这里只有setOnClick,和setBannerPageOnClick()方法，没有setBannerClickListener

**Comment by duboAndroid** [comment]
我是用的2.0.0

**Comment by pinguo-zhouwei** [comment]
@duboAndroid 就是setBannerPageOnClick

**Comment by pinguo-zhouwei** [comment]
合并issue fixs #28
