### ISSUE TITLE
一张图的时候怎么样禁止滑动切换呢？

### ISSUE THREAD

**Issue by tpnet** [pinguo-zhouwei/MZBannerView#41]

**Comment by pinguo-zhouwei** [comment]
一张图没有滑动切换，具体表现是怎样的？

**Comment by weiqi557** [comment]
app:canloop=“true"，目前只能在布局上写入，代码中并没有对canloop进行设置的方法，可以考虑加上，毕竟一张图禁止滑动的需求还是有的

**Comment by NickTet** [comment]
遇到这个需求了

**Comment by pinguo-zhouwei** [comment]
@NickTet @weiqi557  你的意思是原来多张图，然后动态变为一张图，在代码中禁止滚动吗

**Comment by pinguo-zhouwei** [comment]
已经在v2.0.2版本添加api:
setCanLoop(boolean canLoop),在setPages 之前调用
