### ISSUE TITLE
提出几点建议。

### ISSUE THREAD

**Issue by AnJiuZhe** [pinguo-zhouwei/MZBannerView#46]
1.手指按住或者滑动banner的时候，banner依然会自动轮播。
2.不支持设置indicator距离底部的距离

**Comment by Jibinghao** [comment]
+1 我觉得这个挺有必要处理一下@pinguo-zhouwei

**Comment by JamesMarts** [comment]
第一个问题没遇到，第二个问题确实需要处理一下

**Comment by pinguo-zhouwei** [comment]
@AnJiuZhe @Jibinghao @JamesMarts 手指按住或滑动停止轮播原来就有哈，设置indicator 的位置api 最新版本已经添加
