### ISSUE TITLE
图片模式怎么设置

### ISSUE THREAD

**Issue by clbDream** [pinguo-zhouwei/MZBannerView#54]
比如说ImageView中的android:scaleType="centerCrop"

**Comment by pinguo-zhouwei** [comment]
可以设置啊，布局是你自己通过ViewHolder提供的，

**Comment by clbDream** [comment]
<com.oxnice.client.widget.mzbanner.MZBannerView
                android:id="@+id/banner_goods"
                android:layout_width="match_parent"
                android:layout_height="360dp"
                app:canLoop="true"
                app:indicatorPaddingBottom="5dp"
                app:open_mz_mode="false" />

**Comment by clbDream** [comment]
我没有提供布局啊,直接使用的

**Comment by clbDream** [comment]
//设置是否显示Indicator
        bannerGoods.setIndicatorVisible(false);
        bannerGoods.setBannerPageClickListener(new MZBannerView.BannerPageClickListener() {
            @Override
            public void onPageClick(View view, int position) {
                ToastUtils.showToast(mContext, "onPageClick" + position);
            }
        });
        //设置显示指示器
        bannerGoods.setIndicatorVisible(true);
        // 设置数据
        bannerGoods.setPages(bannerList, new MZHolderCreator<BannerViewHolder>() {
            @Override
            public BannerViewHolder createViewHolder() {
                return new BannerViewHolder();
            }
        });

**Comment by pinguo-zhouwei** [comment]
BannerViewHolder 里就是你自己的布局啊
