### ISSUE TITLE
每重新设置一遍数据onPageSelected调用次数就增加

### ISSUE THREAD

**Issue by 596861134** [pinguo-zhouwei/MZBannerView#64]
第一次    
    addPageChangeLisnter:1
    addPageChangeLisnter:1
第二次
    addPageChangeLisnter:1
    addPageChangeLisnter:1
    addPageChangeLisnter:1

**Comment by pinguo-zhouwei** [comment]
感谢反馈，我查一下

**Comment by pinguo-zhouwei** [comment]
试了一下，没有发现你说的问题，可以加我QQ:549826574,给我看一下具体的表现

**Comment by pinguo-zhouwei** [comment]
问题复现出来了，已经fix,多谢反馈
