### ISSUE TITLE
触摸后,还是按照delay的时间来自动滑动,应该重置自动滑动间隔计时

### ISSUE THREAD

**Issue by jaysowen** [pinguo-zhouwei/MZBannerView#65]
比如默认自动滑动时间是间隔5秒,目前正在显示第二张banner.我在第4秒的时候右滑回到第一张banner.这个时候过1秒之后又自动回到了第二张.给人的感觉就是体验很不好,如果手动滑动之后能够重置一下间隔时间会好很多.

**Comment by pinguo-zhouwei** [comment]
多谢反馈，已经修复，已经在V2.0.2版本修复
