### ISSUE TITLE
当数据源长度为0的时候报异常

### ISSUE THREAD

**Issue by JillFung** [pinguo-zhouwei/MZBannerView#66]
数据源长度为0：
  Caused by: java.lang.ArithmeticException: divide by zero
导致Banner图没法更新

**Comment by JillFung** [comment]
您好，如果您看到这条消息，请您能及时回复我，以为我在线上的项目中使用了您的项目。
在我的项目中，存在轮播图的数据源为空的情况，但是现在数据源如果为空会崩溃。请问有什么方法能在数据源为空的时候，清空轮播图的数据呢？急急急！谢谢

**Comment by pinguo-zhouwei** [comment]
感谢反馈，已经修复，请更新最新版本
