### ISSUE TITLE
自己修改源代码，增加添加banner功能，但是数据无法及时刷新

### ISSUE THREAD

**Issue by Mite95** [pinguo-zhouwei/MZBannerView#79]
/**
  * 增加banner
  */
 public void addBannerPage(List<T> datas) {
        mAdapter.setDatas(datas);
        initIndicator();
        mViewPager.getAdapter().notifyDataSetChanged();
    }

但是增加之后，banner展示是数据会是之前的，滚动隐藏新增加数据会出现一条，不会立刻全部更新

**Comment by pinguo-zhouwei** [comment]
你改了源码这个就不太清楚了
