### ISSUE TITLE
刷新

### ISSUE THREAD

**Issue by qq425729** [pinguo-zhouwei/MZBannerView#8]
这怎么刷新呢?求教

**Comment by 2966325911** [comment]
你的意思是修改里面的图片吗？可以重新设置数据源

**Comment by pinguo-zhouwei** [comment]
你说的刷新是像RecyclerView 的Adapter的notifyChange吗？因为没有暴露Adapter，所以重新调用setPages重新设置数据就好

**Comment by qq425729** [comment]
恩 重新数据源 调用setPages可以了 谢谢 但是会重复addOnPageChangeListener,之后我把mViewPager的监听先remove掉再添加就好了

**Comment by ToastYang** [comment]
为什么我刷新 会直接说数组下标越界

**Comment by ToastYang** [comment]
当图片里面的数量有所增加就会直接崩溃，但有所减少不会
