### ISSUE TITLE
支持kotlin吗

### ISSUE THREAD

**Issue by clbDream** [pinguo-zhouwei/MZBannerView#80]
我在kotlin里面写,报了一个错
Out-projected type 'MZBannerView<*>!' prohibits the use of 'public open fun setPages(datas: (Mutable)List<T!>!, mzHolderCreator: MZHolderCreator<(raw) MZViewHolder<*>!>!): Unit defined in com.oxnice.client.widget.mzbanner.MZBannerView'

**Comment by pinguo-zhouwei** [comment]
你能贴一下你的代码吗？
我用kotlin试了一下没问题：
```java

class MainActivity : AppCompatActivity() {
    private var mBanner:MZBannerView<Any>? = null
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        mBanner = findViewById(R.id.banner)

        var listString = listOf(R.drawable.banner1,R.drawable.banner2,R.drawable.banner3)
        mBanner?.setPages(listString, {
            BannerViewHolder()
        })
    }

    override fun onResume() {
        super.onResume()
        mBanner?.start()
    }

    override fun onPause() {
        super.onPause()
        mBanner?.pause()
    }

}

class BannerViewHolder:MZViewHolder<Int>{
    private var mImageView:ImageView? = null
    override fun onBind(p0: Context?, p1: Int, p2: Int?) {
        if (p2 != null) {
            mImageView?.setImageResource(p2)
        }
    }

    override fun createView(context: Context?): View {
        val view = LayoutInflater.from(context).inflate(R.layout.banner, null)
        mImageView = view.findViewById(R.id.image_view)
        return view
    }

}
```

**Comment by CasparGX** [comment]
很多人用Anko这个库，所以不会在页面里面写
`private var mBanner:MZBannerView<Any>? = null`
以及
`mBanner = findViewById(R.id.banner)`
一般控件都是anko库直接帮我们绑定了，所以调用`mBanner.setPages()`的时候就会报泛型错误
用anko绑定控件的需要对控件强制转换一下：
**(banner_module as MZBannerView<Any>)**.setPages(listString, { BannerViewHolder() })

**Comment by duxun** [comment]
也是泛型问题，这样写setPages 会提示报错
 private fun setData(data: MainDateBean) {
        var listString: ArrayList<String> = ArrayList()
        for (i in 0 until data.data.middle_advert.size) {
            listString.add(data.data.middle_advert[i].image)
        }
        main_fragment_banner?.run {
            setPages(listString, com.zhouwei.mzbanner.holder.MZHolderCreator<BannerViewHolder> { BannerViewHolder() })
            setDelayedTime(3 * 1000)
            setIndicatorVisible(false)
            start()
        }
    }
