### ISSUE TITLE
###手势问题   作者实现了 按压停止轮滑，但移动按压手势没写导致轮播图停止

### ISSUE THREAD

**Issue by ehnait** [pinguo-zhouwei/MZBannerView#81]
当手指按压 轮播图时--->轮播图停止 --->手指保持按压状态向上移动--->释放手指--->轮播图停止自动轮播了

**Comment by ehnait** [comment]
@Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        if (!mIsCanLoop) {
            return super.dispatchTouchEvent(ev);
        }
        switch (ev.getAction()) {
            // 按住Banner的时候，停止自动轮播
            case MotionEvent.ACTION_MOVE:
            case MotionEvent.ACTION_CANCEL:
                start();//建议在这里加上start()
                break;
            case MotionEvent.ACTION_OUTSIDE:
            case MotionEvent.ACTION_DOWN:
                int paddingLeft = mViewPager.getLeft();
                float touchX = ev.getRawX();
                // 如果是魅族模式，去除两边的区域
                if (touchX >= paddingLeft && touchX < getScreenWidth(getContext()) - paddingLeft) {
                    pause();
                }
                break;
            case MotionEvent.ACTION_UP:
                start();
                break;
        }
        return super.dispatchTouchEvent(ev);

**Comment by pinguo-zhouwei** [comment]
收到，谢谢建议和反馈
